version: '3'

services:
  server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app

  client:
    image: node:18
    working_dir: /app
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    command: sh -c "cd client && npm install && npm start"
